# Question 1: 

Note: The index of site 1 is start with zero index of the traffic_data which is in row.
      The index of month 1 is start with zero index of the traffic_data which is in column.

Question 1(a) Read the dataset using numpy package

In [1]:
import numpy as np
traffic_data = np.loadtxt('ques1_data.txt', delimiter=',') 
#here we load the text file whose name ques1_data

In [2]:
print(traffic_data) # here we print the traffic data

[[ 550.  764.  803.  525.  964.  611.  506.  752.  577.  967.  682.  788.]
 [ 864.  521.  983.  512.  556.  716.  856.  711.  889.  954.  831.  998.]
 [ 832.  902.  569.  728.  551.  543.  580.  881.  805.  804.  872.  574.]
 [ 829.  797.  547.  845.  772.  822.  586.  753.  871.  976.  833.  708.]
 [ 975.  809.  707.  919.  533.  681.  711.  538.  541.  739.  722.  766.]
 [ 847.  641.  874.  719.  598.  954.  573.  726.  970.  583.  552.  680.]
 [ 965.  581.  633.  616.  734.  903.  535.  783.  868.  845.  591.  854.]
 [ 745.  547.  889.  885.  747.  581.  823.  612.  582.  878.  590.  968.]
 [ 718.  670.  590.  587.  698.  881.  666.  856.  654.  795.  823.  908.]
 [ 900.  609.  990.  997.  509.  565.  834.  882.  615.  901.  754.  629.]
 [ 627.  669.  972.  969.  821.  510.  589.  997.  763.  743.  975.  760.]
 [ 973.  982.  690.  534.  500.  507.  760.  710.  898.  804.  901.  752.]
 [ 524.  882.  990.  749.  642.  536.  867.  951.  587.  987.  971.  613.]
 [ 937.  871.  819.  704.

Question 1(b) find out the number of sites for each traffic volume data is present

In [3]:
number_of_site= traffic_data.shape[0] 
# here we find the number of rows in the file which is equal to number of site
print(number_of_site)

50


Question 1(c) Find out the monthly average traffic (MAT) volume for each site (Hint: add traffic volume of 12 months for each                 site and divide by 12). Store it as an array and show the output of MAT for the first 5 sites (Site 1, Site 2, …,               Site 5)


In [4]:
sum_of_row_traffic_data= traffic_data.sum(axis=1) 
# this prints the row wise sum of the data
avg_traffic_data_site=traffic_data.sum(axis=1)/12
print(avg_traffic_data_site[:5]) # print average traffic data of first five site

[707.41666667 782.58333333 720.08333333 778.25       720.08333333]


In [5]:
# show the output of MAT for the first five month
sum_of_traffic_data_each_month= traffic_data.sum(axis=0) 
# this prints the column wise sum of the data
mat = sum_of_traffic_data_each_month/12 # mat= monthly average traffic data 
print(mat[:5]) # here we print the first five mat data of month

[3101.83333333 3112.75       3080.33333333 3096.58333333 3095.08333333]


Question 1(d) Which site has maximum total yearly volume and which site has minimum yearly volume?

In [6]:
index_max_traffic_data= np.argmax(sum_of_row_traffic_data) 
# find the index of max traffic data which is site
print(index_max_traffic_data) # print index of max traffic data 
index_min_traffic_data= np.argmin(sum_of_row_traffic_data) 
# find the index if min traffic data which is site
print(index_min_traffic_data)# print index of min traffic data


33
36


Question 1(e) What is the maximum and minimum yearly volume?

In [16]:
print(sum_of_row_traffic_data.max()) 
#to find the max traffic data
print(sum_of_row_traffic_data.min())
# to find the min traffic data

10108.0
7759.0


Question 1(f) Which month experienced maximum traffic volume across all sites and which month experienced minimum traffic volume across all sites?

In [8]:

index_max_traffic_month= np.argmax(sum_of_traffic_data_each_month) 
# to find which month has max traffic
print(index_max_traffic_month)

index_min_traffic_month= np.argmin(sum_of_traffic_data_each_month) 
# to find which month has min traffic
print(index_min_traffic_month)


9
5


Question 1(g) Which sites has total yearly volume > 9700 vehicles?

In [9]:
required_cond1=(sum_of_row_traffic_data>9700)
total_site=np.where(required_cond1) 
# to find no. of site where traffic volume greater than 9700
print(total_site)

(array([17, 27, 33, 34, 45], dtype=int64),)


Question 1(h) Determine the months where the total monthly volume for the entire city (sum of monthly volume for all sites) is               greater than 38,000 vehicles.


In [10]:
required_cond2=(sum_of_traffic_data_each_month>38000)
total_month=np.where(required_cond2) 
# to find month where traffic volume greater than 38000
print(total_month)

(array([ 9, 10], dtype=int64),)


# Question 2: 

Question 2(a) Store this tweet as a single string in python.

In [19]:
x_tweet='''Neeraj Chopra brings home the much awaited Gold First place 
medal for Flag of India in his debut Olympic Games. The gigantic effort
made sure India has best ever medal haul in the olympics. Congratulations
champ Neeraj Chopra , the whole nation is proud of you''' 
# to store it in single string
print(x_tweet)

Neeraj Chopra brings home the much awaited Gold First place 
medal for Flag of India in his debut Olympic Games. The gigantic effort
made sure India has best ever medal haul in the olympics. Congratulations
champ Neeraj Chopra, the whole nation is proud of you


Question 2(b) Split the string into a list with each element of the list being each word of the tweet. Output the list

In [20]:
split_words = x_tweet.split() # split() function is used to split the words.
print(split_words)

['Neeraj', 'Chopra', 'brings', 'home', 'the', 'much', 'awaited', 'Gold', 'First', 'place', 'medal', 'for', 'Flag', 'of', 'India', 'in', 'his', 'debut', 'Olympic', 'Games.', 'The', 'gigantic', 'effort', 'made', 'sure', 'India', 'has', 'best', 'ever', 'medal', 'haul', 'in', 'the', 'olympics.', 'Congratulations', 'champ', 'Neeraj', 'Chopra,', 'the', 'whole', 'nation', 'is', 'proud', 'of', 'you']


Question 2(c) How many words are present in the tweet?

In [13]:
total_number_of_element = len(split_words) 
# this function counts the number of words
print(total_number_of_element)

45


Question 2(d) How many unique words are present in the tweet?

In [14]:
set_element= set(split_words)# this function converts the list into set
print(set_element)

{'haul', 'Flag', 'brings', 'proud', 'you', 'has', 'Games.', 'Olympic', 'olympics.', 'Chopra', 'First', 'India', 'effort', 'awaited', 'of', 'ever', 'Neeraj', 'much', 'medal', 'in', 'home', 'nation', 'The', 'the', 'place', 'for', 'whole', 'debut', 'best', 'is', 'gigantic', 'champ', 'Chopra,', 'made', 'sure', 'his', 'Gold', 'Congratulations'}


In [15]:
total_number_unique_element=len(set_element)
# this function is used to find no. of element in the set which are unque elements
print(total_number_unique_element)

38
